### ISSUE TITLE
Does the agent support GPT, Gemini, Claude, etc.

### ISSUE THREAD

**Issue by zsqdx** [togethercomputer/MoA#16]
Hello contributors! I just want to know whether the agent supports GPT, Gemini, Claude, etc. as proposers. Thanks.

**Comment by erik-sv** [comment]
I iterated on sammcj's fork. It should work with any OpenAI formatted endpoint, including local models. I have tested LM Studio and Groq. Just create your own .env file based on the .env.template file where the first API is what you want your proposers to be, and API_2 is what you want your aggregator to be. https://github.com/erik-sv/MoA
