### ISSUE TITLE
Agents?

### ISSUE THREAD

**Issue by logan-markewich** [togethercomputer/MoA#7]
Just curious, I found the title of the approach pretty confusing. "Mixture of Agents" to me implies some agentic behaviour -- LLMs using tools and decision making to accomplish a task.

However, if I'm correct, theres no agentic behaviour, tool use, or decision making here. Instead, the proposed method is more of a "Mixture of LLMs", where LLM calls are combined and iterated on.

Is my understanding correct?

**Comment by jonathanpv** [comment]
I agree, and it's unclear if its modifying the hidden states of the LLM or not from the image, after further reading it seems like its just a chain of prompts concatenated

**Comment by logan-markewich** [comment]
Yea from my understanding, it's just concatenating and aggregating outputs of LLMs

**Comment by IsThatYou** [comment]
Thank you for your feedbacks! We are sorry for confusion over terminology here. We here treat each LLM as a conversational agent in MoA. Following the definition in [1] [2], we consider an agent as a system that can use observations maintain internal states and execute actions with **LLM functioning as the brain** with some components -- **planning**, **memory**, or **tool use**. In MoA, each agent is maintaining previous rounds responses (memory) and refine on top of them (planning). Therefore, an agent doesn't need to have tool use to be an agent. But we do believe tool use is very critical here, and people do associate agent with tool use pretty heavily. This would definitely be a very interesting extension to see if collabraotiveness help with the ability for tool use! We will try this soon and please stay tuned! Thank you again!

[1] https://arxiv.org/abs/2212.01681

[2] https://lilianweng.github.io/posts/2023-06-23-agent/
